# Generated by Django 3.2.16 on 2023-02-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
